package com.trainingdataprocessor.regex;

import com.trainingdataprocessor.tags.EncodedTags;

/**
 * Created by Oliver on 9/19/2016.
 */
public final class RegexExpressions {

    private static final String BEFORE_VERB_PREPOSITION_PHRASE = "[#NJD$@]?[PT]?";

    private static final String BEFORE_VERB_NOUN_PHRASE = "[NJD]*N[A]?";

    private static final String AFTER_VERB_NOUN_PHRASE = "[#NJD$@A]*";

    private static final String AFTER_VERB_PREPOSITION_PHRASE = "[PT]?[Y#NJD$V]*";

    private static final String ADVERB_SEQUENCE = "[A]*";

    public static final String IS_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE + EncodedTags.IS_ARE + AFTER_VERB_NOUN_PHRASE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;

    public static final String IS_NOT_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE + EncodedTags.IS_ARE + EncodedTags.NOT + AFTER_VERB_NOUN_PHRASE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;

    public static final String VERB_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE + "[" + EncodedTags.VERB + EncodedTags.VERB_ED + "]" + AFTER_VERB_NOUN_PHRASE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;

    public static final String VERB_DONT_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE + EncodedTags.DO + "[" + EncodedTags.VERB + EncodedTags.VERB_ED + "]" + AFTER_VERB_NOUN_PHRASE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;

    public static final String VERB_DO_NOT_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE + EncodedTags.DO + EncodedTags.NOT +
            "[" + EncodedTags.VERB + EncodedTags.VERB_ED + "]" + AFTER_VERB_NOUN_PHRASE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;

    public static final String MODAL_VERB_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE +
            EncodedTags.MODAL_VERB + ADVERB_SEQUENCE + EncodedTags.VERB + ADVERB_SEQUENCE +
            AFTER_VERB_NOUN_PHRASE + ADVERB_SEQUENCE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;

    public static final String MODAL_VERB_NOT_RELATIONSHIP_PATTERN = BEFORE_VERB_PREPOSITION_PHRASE + BEFORE_VERB_NOUN_PHRASE +
            EncodedTags.MODAL_VERB + EncodedTags.NOT + ADVERB_SEQUENCE + EncodedTags.VERB + ADVERB_SEQUENCE +
            AFTER_VERB_NOUN_PHRASE + ADVERB_SEQUENCE +
            AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE + AFTER_VERB_PREPOSITION_PHRASE;


}
